platform :ios, '12.0'
use_frameworks!
workspace 'UserDataApp'


def rx_pods
  pod 'NSObject+Rx'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
end
 

target 'UserDataApp' do
  project 'UserDataApp/UserDataApp.xcodeproj'
  pod 'SnapKit'
  pod 'SwiftyBeaver'
  pod 'PhoneNumberKit', '~> 3.3'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'IQKeyboardManagerSwift'
  rx_pods
end


target 'UserDataAppBase' do
  project 'UserDataAppBase/UserDataAppBase.xcodeproj'
  rx_pods
end

post_install do |installer|
      installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
                config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
           end
      end
 end

